[build-system]
requires = ["setuptools >= 80.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mbe_software"
version = "0.1.0"

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
mbe-software = "mbe_software.app:start"