devices:
  pressure:
    - name: Growth Ion
      address: 0
    - name: Flux Ion
      address: 1
    - name: Intro Ion
      address: 2
    - name: Intro Thermocouple
      address: 3

  shutters:
    - name: Aluminum
      address: 0
    - name: Scandium
      address: 1
    - name: none
      address: 2
    - name: Magnesium
      address: 3
    - name: Gallium
      address: 4
    - name: Indium
      address: 5
    - name: Silicon
      address: 6
    - name: Beryllium
      address: 7

  sources:
    effusion_cell:
      - name: Gallium
        device_id: 0
      - name: Scandium
        device_id: 1
      - name: Beryllium
        device_id: 2
      - name: Aluminum
        device_id: 3
      - name: Indium
        device_id: 4
      - name: Silicon
        device_id: 5
      - name: Substrate
        device_id: 6
      - name: Intro
        device_id: 7
      - name: N/A
        device_id: 8
    
    mg_bulk:
      - name: Mg Bulk PID
        device_id: 9
      - name: Mg Bulk DC
        device_id: 10
    
    mg_cracker:
      - name: Mg Cracker PID
        device_id: 11
      - name: Mg Cracker DC
        device_id: 12

serial:
  shutters:
    port: COM8

  diffusion_cells:
    port: COM10

  ga_bulk_pid:
    port: COM11

  ga_bulk_dc:
    port: COM12

  ga_cracker_pid:
    port: COM13

  ga_cracker_dc:
    port: COM14