devices:
  pressure:
    'null':
      serial:
        port: null
        baudrate: 9600
      connections:
      - name: Growth Ion
        address: 0
      - name: Flux Ion
        address: 1
      - name: Intro Ion
        address: 2
      - name: Intro Thermocouple
        address: 3
  sources:
    'null':
      serial:
        port: null
        baudrate: 9600
      connections:
      - name: Gallium
        device_id: 1
        address_set: loop_1
      - name: Scandium
        device_id: 1
        address_set: loop_2
      - name: Beryllium
        device_id: 2
        address_set: loop_1
      - name: Aluminum
        device_id: 2
        address_set: loop_2
      - name: Indium
        device_id: 3
        address_set: loop_1
      - name: Silicon
        device_id: 3
        address_set: loop_2
      - name: Substrate
        device_id: 4
        address_set: loop_1
      - name: Intro
        device_id: 4
        address_set: loop_2
      - name: Mg Bulk PID
        device_id: 4
        address_set: loop_1
      - name: Mg Cracker PID
        device_id: 5
        address_set: loop_1
  shutters:
    'null':
      serial:
        port: null
        baudrate: 9600
      connections:
      - name: Gallium
        address: 0
      - name: Scandium
        address: 0
      - name: Beryllium
        address: 0
      - name: Aluminum
        address: 0
      - name: Indium
        address: 0
      - name: Silicon
        address: 7
